[project]
name = "scale_io"
version = "0.2.0"
description = "Default template for PDM package"
authors = [
    {name = "elnath1002", email = "elnath1002@naver.com"},
]
dependencies = []
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = true
